// <auto-generated />
using BancoNacional.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoNacional.Data.Migrations
{
    [DbContext(typeof(BancoNacionalDbContext))]
    [Migration("20220107193825_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BancoNacional.Models.Agencias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GERENTE")
                        .HasColumnType("int");

                    b.Property<string>("LOCALIZACAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NUMERO_CLIENTES")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AGENCIAS");
                });

            modelBuilder.Entity("BancoNacional.Models.Clientes", b =>
                {
                    b.Property<int>("CODIGO_CLIENTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CODIGO_CLIENTE"), 1L, 1);

                    b.Property<int>("CODIGO_AGENCIA")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SALDO")
                        .HasColumnType("int");

                    b.Property<int>("TIPO_CONTA")
                        .HasColumnType("int");

                    b.HasKey("CODIGO_CLIENTE");

                    b.ToTable("CLIENTES");
                });

            modelBuilder.Entity("BancoNacional.Models.ContaCorrente", b =>
                {
                    b.Property<int>("CODIGO_CONTA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CODIGO_CONTA"), 1L, 1);

                    b.Property<string>("DONO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CODIGO_CONTA");

                    b.ToTable("CONTA_CORRENTE");
                });

            modelBuilder.Entity("BancoNacional.Models.ContaPoupanca", b =>
                {
                    b.Property<int>("CODIGO_CONTA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CODIGO_CONTA"), 1L, 1);

                    b.Property<string>("DONO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CODIGO_CONTA");

                    b.ToTable("CONTA_POUPANCA");
                });

            modelBuilder.Entity("BancoNacional.Models.Gerentes", b =>
                {
                    b.Property<int>("CODIGO_GERENTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CODIGO_GERENTE"), 1L, 1);

                    b.Property<int>("CODIGO_AGENCIA")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CODIGO_GERENTE");

                    b.ToTable("GERENTES");
                });
#pragma warning restore 612, 618
        }
    }
}
